"""Pure data + filesystem layer for the setup wizard.

This module knows nothing about user interaction.  It only:

* defines the :class:`Setting` / :class:`Section` value objects
* provides validators that map a string to ``None`` (ok) or an error message
* loads / writes ``.env`` files
* enumerates the wizard's sections via :func:`build_sections`

Both the CLI and the GUI views import from here so the wizard stays in
sync regardless of how the user drives it.
"""

from __future__ import annotations

import secrets
import string
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional

# setup_wizard/  ->  <repo>/
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ENV_PATH = REPO_ROOT / ".env"


def validate_optional(_: str) -> Optional[str]:
    return None


def validate_required(value: str) -> Optional[str]:
    return None if value.strip() else "value is required"


def validate_path_exists_optional(value: str) -> Optional[str]:
    if not value.strip():
        return None
    return None if Path(value).expanduser().exists() else f"path does not exist: {value}"


def validate_port(value: str) -> Optional[str]:
    if not value.strip():
        return None
    try:
        port = int(value)
    except ValueError:
        return "must be a number"
    return None if 1 <= port <= 65535 else "must be between 1 and 65535"


def validate_uid(value: str) -> Optional[str]:
    if not value.strip():
        return None
    try:
        n = int(value)
    except ValueError:
        return "must be a number"
    return None if n >= 0 else "must be >= 0"


@dataclass
class Setting:
    """A single key=value pair the wizard collects from the user."""

    key: str
    label: str
    default: str = ""
    help_text: str = ""
    validator: Callable[[str], Optional[str]] = validate_optional
    secret: bool = False
    # Skip writing this key to .env when the value is empty.
    skip_if_empty: bool = True


@dataclass
class Section:
    """A logical grouping of related settings."""

    title: str
    description: str = ""
    settings: list[Setting] = field(default_factory=list)


def load_existing_env(path: Path) -> dict[str, str]:
    """Parse a previously-written ``.env`` and return its key/value map."""

    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v
    return out


def write_env(path: Path, values: dict[str, str]) -> None:
    """Write ``values`` to ``path`` in a stable, comment-friendly format."""

    header = (
        "# Generated by setup_wizard - re-run the wizard to update.\n"
        "# See .env.example for the full annotated reference.\n"
        "\n"
    )
    body = "\n".join(f"{k}={v}" for k, v in values.items())
    path.write_text(header + body + "\n", encoding="utf-8")


def random_password(length: int = 24) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def build_sections(existing: dict[str, str]) -> list[Section]:
    """Return the full list of sections the wizard walks through.

    ``existing`` is consulted for default values so re-running the wizard
    on top of an existing ``.env`` is non-destructive.
    """

    def d(key: str, fallback: str = "") -> str:
        return existing.get(key, fallback)

    return [
        Section(
            "Source tree",
            "Required for the local-source dev / debug builds. Leave blank "
            "if you only intend to build the production image (which clones "
            "the source over the network).",
            [
                Setting(
                    "MUMBLE_SRC",
                    "Local mumble-server source path",
                    default=d("MUMBLE_SRC"),
                    help_text="Absolute path to a clone of "
                              "https://github.com/SetZero/mumble-server",
                    validator=validate_path_exists_optional,
                ),
            ],
        ),
        Section(
            "Image & container names",
            "All build / run helpers honour these.",
            [
                Setting("MUMBLE_IMAGE", "Image name",
                        default=d("MUMBLE_IMAGE", "mumble-server")),
                Setting("MUMBLE_TAG", "Default image tag",
                        default=d("MUMBLE_TAG", "dev"),
                        help_text="Each helper script overrides this with a sensible "
                                  "default (dev/debug/vanilla); only set to force one."),
                Setting("MUMBLE_CONTAINER", "Container name",
                        default=d("MUMBLE_CONTAINER", "mumble-server")),
                Setting("MUMBLE_DATA_VOLUME", "Named volume for /data",
                        default=d("MUMBLE_DATA_VOLUME", "mumble-data")),
            ],
        ),
        Section(
            "Network ports",
            "Host-side ports.  Container-side ports are fixed by the Dockerfile.",
            [
                Setting("MUMBLE_PORT",
                        "Mumble voice / control port (TCP+UDP)",
                        default=d("MUMBLE_PORT", "64738"), validator=validate_port),
                Setting("MUMBLE_FILESERVER_PORT",
                        "File-server HTTP port (TCP)",
                        default=d("MUMBLE_FILESERVER_PORT", "64739"), validator=validate_port),
                Setting("MUMBLE_SFU_PORT",
                        "WebRTC SFU port (UDP)",
                        default=d("MUMBLE_SFU_PORT", "10000"), validator=validate_port),
            ],
        ),
        Section(
            "Runtime user",
            "UID/GID used inside the debug container.  Must match the "
            "ownership of any files you mount from the host.",
            [
                Setting("MUMBLE_UID", "Container UID",
                        default=d("MUMBLE_UID", "1000"), validator=validate_uid),
                Setting("MUMBLE_GID", "Container GID",
                        default=d("MUMBLE_GID", "1000"), validator=validate_uid),
            ],
        ),
        Section(
            "Server admin",
            "Optional.  When set, the helper scripts configure SuperUser "
            "after first start.  Leave blank to let the server generate a "
            "random one (printed to the container log).",
            [
                Setting("MUMBLE_SUPERUSER_PASSWORD",
                        "SuperUser password",
                        default=d("MUMBLE_SUPERUSER_PASSWORD"),
                        secret=True),
            ],
        ),
        Section(
            "Optional file mounts",
            "Absolute host paths used by the local dev/debug helper scripts.\n"
            "Leave blank to skip.",
            [
                Setting("MUMBLE_INI",
                        "Custom mumble-server.ini to mount",
                        default=d("MUMBLE_INI"),
                        help_text="Mounted read-only at /data/mumble-server.ini.",
                        validator=validate_path_exists_optional),
            ],
        ),
        Section(
            "Firebase Cloud Messaging (push notifications)",
            "FCM credentials let the server send push notifications to mobile/desktop\n"
            "clients.  Leave blank to disable push notifications.\n"
            "\n"
            "Recommended: encode the JSON key as base64 and set\n"
            "MUMBLE_FCM_CREDENTIALS_BASE64 in .env or as a container secret.\n"
            "This avoids exposing the file path on the host and prevents the\n"
            "credentials from accidentally entering a Docker image layer.",
            [
                Setting("MUMBLE_FCM_CREDENTIALS",
                        "Path to FCM service-account JSON (for dev scripts)",
                        default=d("MUMBLE_FCM_CREDENTIALS"),
                        help_text="Used by dev-build / dev-debug to mount the file at runtime.\n"
                                  "Never committed; pattern is gitignored.",
                        validator=validate_path_exists_optional),
                Setting("MUMBLE_FCM_CREDENTIALS_BASE64",
                        "Base64-encoded FCM JSON (for container env / secrets)",
                        default=d("MUMBLE_FCM_CREDENTIALS_BASE64"),
                        help_text="Paste a base64-encoded copy of the JSON key, OR leave\n"
                                  "blank and the wizard will encode the path above for you."),
            ],
        ),
        Section(
            "Upstream source (production Dockerfile)",
            "Override these to build the production image from a different "
            "fork or branch.  Defaults match the Fancy Mumble server fork.",
            [
                Setting("MUMBLE_GIT_REPO", "Server source repo URL",
                        default=d("MUMBLE_GIT_REPO", "https://github.com/SetZero/mumble-server")),
                Setting("MUMBLE_GIT_BRANCH", "Server source branch",
                        default=d("MUMBLE_GIT_BRANCH", "1.6.x")),
            ],
        ),
        Section(
            "Multi-arch publish (buildx.sh)",
            "Only used by buildx.sh.  Leave blank if you don't publish.",
            [
                Setting("BUILDX_IMAGE", "Target image (e.g. myorg/mumble-server:1.6.0)",
                        default=d("BUILDX_IMAGE")),
                Setting("BUILDX_PLATFORMS", "Comma-separated platforms",
                        default=d("BUILDX_PLATFORMS", "linux/amd64,linux/arm64")),
            ],
        ),
    ]
