name: CI

on: [ push, pull_request ]

jobs:
    build_latest:
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "latest"
            docker_version: '0'
            publish: false
            update_latest: true
