name: CI

on: [ push, pull_request ]

jobs:
    build_latest:
        permissions:
            packages: write
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "latest"
            docker_version: '0'
            store: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
            publish: false
            update_latest: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        secrets: inherit
